### ISSUE TITLE
Relaton local cache does not store "fetched" attribute

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/relaton#16] opened 2018-10-23 20:30 UTC
Relaton local cache now fetches every single time because the "fetched" data element is not provided in the local cache entry. @andrew2net can you help fix this? Thanks!

**Comment by andrew2net** [comment] 2018-10-24 10:10
Yes, the fetched element was missed in `IsoBibliographicItem.to_xml`. Fixed it. Now it needs to publish last `iso-bib-item` gem or install it locally.

**Comment by ronaldtse** [comment] 2019-02-08 15:00
@andrew2net is this all done? Thanks!

**Comment by andrew2net** [comment] 2019-02-08 17:45
@ronaldtse it is fixed but I don't know if it is published. @opoudjis manages versions.

**Comment by opoudjis** [comment] 2019-03-09 11:50
Yes, "fetched" is being retrieved, and is confirmed as retrieved in the iso-bib-item rspec. There have been three gem releases of iso-bib-item since Oct 24. Closing.

**Closed by opoudjis** 2019-03-09 11:50 UTC
Labels: bug
